### PR TITLE
Fix dirtyness propagation optimization to work fine with tweaks

### LINKED ISSUE #2047: Error with digital-write, evaluate_on_pin disable.
### Environment

* Scope: desktop IDE
* Version: 0.35.2 
* OS: Windows 10 

### Steps to reproduce

With the next patch

ba185a9b9c904510fd1d8ae0e718499317cba5ad 1

### Temporary solution.

In order to compile I have to comment this line in digital-write node

`//#pragma XOD evaluate_on_pin disable`

### Error

```
Begin compiling code for the board Arduino Uno 📦


C:\Users\Cesar\AppData\Local\Temp\xod_temp_sketchbook98XhiA\xod_1601190379205_sketch\xod_1601190379205_sketch.ino: In function 'void xod::detail::handleDebugProtocolMessages()':
C:\Users\Cesar\AppData\Local\Temp\xod_temp_sketchbook98XhiA\xod_1601190379205_sketch\xod_1601190379205_sketch.ino:1331:35: error: 'struct xod::TransactionState' has no member named 'node_0_isOutputDirty_OUT'; did you mean 'node_2_isOutputDirty_TICK'?
                     g_transaction.node_0_isOutputDirty_OUT = true;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~
                                   node_2_isOutputDirty_TICK

C:\Users\Cesar\AppData\Local\Temp\xod_temp_sketchbook98XhiA\xod_1601190379205_sketch\xod_1601190379205_sketch.ino: In function 'void xod::runTransaction()':
C:\Users\Cesar\AppData\Local\Temp\xod_temp_sketchbook98XhiA\xod_1601190379205_sketch\xod_1601190379205_sketch.ino:1391:55: error: 'struct xod::TransactionState' has no member named 'node_0_isOutputDirty_OUT'; did you mean 'node_2_isOutputDirty_TICK'?
             ctxObj._isOutputDirty_OUT = g_transaction.node_0_isOutputDirty_OUT;
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
                                                       node_2_isOutputDirty_TICK

Error during build: exit status 1
```

[forum XOD](https://forum.xod.io/t/error-with-digital-write/4466)

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #2047 

The bug was introduced in the 0.33.0 right in the commit https://github.com/xodio/xod/commit/0880f41e252d8e000ade77b5efdb65d28857eba3 😬

### CODE REVIEW

**Review by nkrkv — COMMENTED** [review]
Wouldn’t it be more appropriate to move this business logic out of the template, to the helper definitions or even further? Templates are harder to maintain.

**Comment by evgenykochetkov** [comment]
If I understand #2047 correctly, the following is happening: 

`digital-write` node that wants to update only when `UPD` pin is touched, as stated by
```
#pragma XOD evaluate_on_pin disable
#pragma XOD evaluate_on_pin enable input_UPD
```

but the code generated in `handleDebugProtocolMessages `
https://github.com/xodio/xod/blob/faf25a86cec036638306768886562b314805313b/packages/xod-arduino/platform/program.tpl.cpp#L149-L150
(and maybe in some other place?) does not respect that.

I think that forcing generation of `node_NNN_isOutputDirty_XXX` and marking nodes as dirty in such situation is not right. The role of tweak node connected to pin with `evaluate_on_pin` disabled should be reduced to just storing the received value, and marking the pin and node dirty should be skipped.

**Comment by brusherru** [comment]
@nkrkv @evgenykochetkov check it out again, please :)

**Review by evgenykochetkov — APPROVED** [review]
LGTM👍🏻

**Review by nkrkv — APPROVED** [review]
:+1:

**Pull request merged**
