### PR TITLE
Brand-new look of Project Browser

### LINKED ISSUE #928: Clear project browser UI
### Mockup

preview

### Icons

- [project.zip](https://github.com/xodio/xod/files/1527894/project.zip)
- [libs.zip](https://github.com/xodio/xod/files/1527897/libs.zip)
- [context-tools-list.zip](https://github.com/xodio/xod/files/1538320/context-tools-list.zip)
- [add-lib.zip](https://github.com/xodio/xod/files/1538322/add-lib.zip)
- [new.zip](https://github.com/xodio/xod/files/1538520/new.zip)

### Acceptance criteria

- The colorful icons are used
- The current node filter/tab is removed
- Splitters are drawn as in the mockup
- Patch actions are hidden in the context menu

### PR DESCRIPTION
**Pull request by brusherru**
It closes #928

### CODE REVIEW

**Comment by nkrkv** [comment]
Beautiful!

Few things I’ve noted:

- “Project Browser” should be Title Cased to keep UI consistent
- The context menu icon is not pixel-perfect (not sure whether it’s a problem of the art or wrong container size override)
- Now we have patch titles (i.e. native tooltips) for nothing. Let’s remove them
- A click on context menu item should raise the popup (as it currently does) *and* set the selection to that Project Browser item
- The selected item highlight style should have a higher priority over hovered item style. I.e. when hovering a selected item, the line should be purple’ish

**Comment by nkrkv** [comment]
Is it WIP or not?

**Comment by brusherru** [comment]
@nkrkv Nope, this PR is ready for review.
All comments, except "pixel-perfect icon", are done.

**Comment by nkrkv** [comment]
@brusherru Are you sure? I only found 2/4. Would you check?

**Comment by brusherru** [comment]
@nkrkv All done!

**Pull request merged**
