### PR TITLE
New look of patch board with bound values

### LINKED ISSUE #1678: Improve patch board design to show bound values
### Rationale

Hiding nodes’ bound values behind Inspector is like writing a text program with parameter names `openBrowser(url, width, height)` instead of argument values `openBrowser('https://xod.io', 1024, 768)`. Usable, but suboptimal: cannot be easy transferred as an image, cannot be perceived as the whole.

### Mockup

new-patch-board

### Acceptance criteria

- [x] Nodes render as in mockup
- [x] Pins (and generic pins) render as in mockup
- [x] Bound values and pin labels too
- [x] Long values and pin labels are truncated
- [x] Constants do not render their value twice

### Out of scope

- Old projects grid migration
- Links/pins color tweaking

### PR DESCRIPTION
**Pull request by brusherru**
It closes #1678 

Vois-la

### CODE REVIEW

**Comment by evgenykochetkov** [comment]
Also, bound values are not shown in latest the Firefox and Chromium on macOS :(

**Comment by evgenykochetkov** [comment]
values bound to generic pins are not colored:
screen shot 2019-02-13 at 18 44 34

**Comment by brusherru** [comment]
All fixed and tweaked :)

Vois-la-2

**Comment by nkrkv** [comment]
I think it’s a bit better to put node labels 2px higher: 10px top margin instead of 12px

**Pull request merged**
