### PR TITLE
Updating arduino-cli to 0.10

### LINKED ISSUE #1896: Upgrade arduino-cli to >0.6.0
The new version should fix uploading to ESP32 (https://github.com/arduino/arduino-cli/issues/163)

### PR DESCRIPTION
**Pull request by quinkennedy**
fixes #1896 

`yarn test-func` is still reporting some errors in the `xod-cli` package. Some of these are popping up in a simple `master` repository using the older arduino-cli binary. This leads me to believe that some errors are an issue with my environment.

### CODE REVIEW

**Comment by quinkennedy** [comment]
Finally got past all the `arduino-cli` initialization errors. `xod-cli` functional tests seem to be very temperamental, and I can't figure out how to properly debug them.

**Comment by nkrkv** [comment]
Hello and thank you for the contribution! Unfortunately, the update does not work on my machine (Linux). The tests are passing, though. Other devs told they have test failing… they are on macOS. So, very careful testing is required.

Would you share your progress? Are you able to upload programs from within XOD using `arduino-cli`? Are you on macOS, right? What board model do you have?

**Comment by quinkennedy** [comment]
I am unable to select a USB port when I run it on OSX. No USB ports are enumerated in the "upload" dialog. This affects a build on the `master` branch as well as on this feature branch. I'm just testing using `yarn start:electron`. 

Attempting to build a distributable errors out trying to find Mac/Memory.pm which might be fixed in a [newer electron-builder](https://github.com/electron-userland/electron-builder/issues/3990)

**Comment by brusherru** [comment]
I consider that this is not a problem of an old electron builder, because it used only in bundling the production version.
I had the same problems a few times in the past, it might be the same problem, which provided on the edge between NodeJS and Electron versions and `serialport` package.

Read carefully the output of `yarn` and `yarn build` commands, `serialport` package may show warnings. If there is no conflict with NodeJS version rebuilding from the source may help:
`npm rebuild --build-from-source` or try this one: https://serialport.io/docs/guide-installation#electron

**Comment by quinkennedy** [comment]
I was getting a `gyp` error `gyp: No Xcode or CLT version detected!` which didn't make sense since Xcode and CLT _were_ installed. Turns out [reinstalling after upgrading to Catalina](https://medium.com/flawless-app-stories/gyp-no-xcode-or-clt-version-detected-macos-catalina-anansewaa-38b536389e8d) solves that. I will be able to test later.

**Comment by quinkennedy** [comment]
I ran `yarn start:electron` again after fixing my command line tools. I set `XOD_ARDUINO_CLI` to the v0.10 executable. Trying to upload _101-upload_ from the _welcome-to-xod_ tutorials gets stuck at compiling 😞
Screen Shot 2020-05-27 at 11 16 20 AM

**Comment by nkrkv** [comment]
> tutorials gets stuck at compiling

Same here (Linux). At least we are at the same page now.

**Comment by quinkennedy** [comment]
next question: it looks like the compiler is getting stuck when checking for a `.xodworkspace` file. How does this workspace file get created, and why isn't it in my packages/xod-cli/bundle/workspace/ directory? I see it in the root-level workspace/

**Comment by quinkennedy** [comment]
I suspect there is a difference between how the old and new arduino CLI saves sketches. i assume before it would use the path provided as a filename, but now it uses it as a directory, and creates a file inside that directory. i'm still trying to track down the command to test...

**Comment by quinkennedy** [comment]
I'm running into an issue when the code copies arduino libraries into the temp directory. the directories get copied, but no files do.
Screen Shot 2020-06-05 at 11 54 46 PM
The error is 
```
🙈 Error
📓 ENOENT: no such file or directory, open '../../../../../var/folders/7w/hv37xvjx34jfntk0tfp96zwmzk3ccz/T/xod_temp_sketchbooknxhgsE/libraries/README.md'
```
I'll try using [the copy command in `fs-extra`](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/copy.md) instead.

**Comment by quinkennedy** [comment]
I forgot to mention, I'm currently trying to track down these bugs by running `packages/xod-cli/bin/run compile --output=test_output --board=esp8266:esp8266:wifi_slot --workspace=test_workspace --debug packages/xod-cli/bundle/workspace/blink @/main`

**Comment by quinkennedy** [comment]
`xodc boards TTY list boards, creates workspace, stderr is empty, zero exit code` seems to throw an error on OSX unless I run the `arduino-cli board listall` command manually first... not totally sure how to remedy that for the unit tests.

I spent a while getting `xodc compile TTY compile patch, stdout is empty, stderr with messages, zero exit code:` to working on my own computer, which seemed partially to do with arduino-cli creating the sketch in the wrong local directory. I figured providing an absolute directory would remove ambiguity and fix the issue, but it has cropped up on both linux and osx CI tests 😡

**Comment by quinkennedy** [comment]
passes the automated tests 🙌

unfortunately, doesn't fix the issue with failing builds for my newer boards. I originally followed [#163](https://github.com/arduino/arduino-cli/issues/163) to #1896 which inspired me to tackle this pull request. I'm running via `yarn start:electron` after setting the `XOD_ARDUINO_CLI` environment variable, is there a way to confirm it is using the v0.10 arduinoCLI ?

patch: 101-upload in welcome-to-xod project
board: Arduino Uno
result: successful compile, upload, & run from within XOD

patch: 101-upload in welcome-to-xod project
board: [Adafruit ItsyBitsy nRF52840 Express](https://www.adafruit.com/product/4481)
bootloader: 0.2.11 SoftDevice s140 6.1.1
result: successful compile, upload, & run _when exporting code via Arduino IDE_
xod error: [full output from compiler tab](https://pastebin.com/zBN8sbdu)
```
Compilation failed
Command maxBuffer size exceeded
The generated C++ code contains errors. It can be due to a bad node implementation or if your board is not compatible with XOD runtime code. The original compiler error message is above. Fix C++ errors to continue. If you believe it is a bug, report the problem to XOD developers.
```

**to be clear** I do not think this is a regression, I would still consider this valuable to merge into master at this point.

**Comment by evgenykochetkov** [comment]
The `Command maxBuffer size exceeded` error happens because the default value for the respective option in `promisify-child-process` is quite small: https://github.com/jcoreio/promisify-child-process/blob/master/src/index.js#L70 But that's a separate issue.

> I do not think this is a regression. I would still consider this valuable to merge into master at this point.

I absolutely agree! Excellent work ❤️

**Comment by nkrkv** [comment]
So, ready to merge. @quinkennedy, thank you a lot. Would you rebase the branch onto the current `master`? See https://github.com/xodio/xod/blob/master/CONTRIBUTING.md#rebasing-on-master

**Comment by evgenykochetkov** [comment]
Rebased and added a couple tweaks to address `maxBuffer size exceeded` error and unnecessarily verbose compiler output.

**Pull request merged**
